import _ from 'lodash'
import { NextApiRequest, NextApiResponse } from 'next'

export default async function ( req: NextApiRequest, res: NextApiResponse ) {
  if ( req.method !== 'GET' ) {
    return res.status( 400 ).json( { message: 'Method not allowed' } )
  }

  try {
    // const response = await fetch(
    //   `${process.env.API_ENDPOINT}/wp-json/menus/v1/menus/144/?nested=1`,
    //   {
    //     headers: {
    //       Authorization: `Bearer ${process.env.ACCESS_TOKEN}`,
    //     },
    //   }
    // )

    // const data = await response.json()
    const data = [
      {
        ID: 2431,
        post_author: '1',
        post_date: '2022-06-17 04:38:52',
        post_date_gmt: '2022-06-16 11:42:36',
        post_content: '',
        post_title: 'MERN Stack',
        post_excerpt: 'mern',
        post_status: 'publish',
        comment_status: 'closed',
        ping_status: 'closed',
        post_password: '',
        post_name: 'mern-stack',
        to_ping: '',
        pinged: '',
        post_modified: '2022-06-17 04:38:52',
        post_modified_gmt: '2022-06-17 04:38:52',
        post_content_filtered: '',
        post_parent: 0,
        guid: 'https://api-blog.jstemplate.net/?p=2431',
        menu_order: 1,
        post_type: 'nav_menu_item',
        post_mime_type: '',
        comment_count: '0',
        filter: 'raw',
        db_id: 2431,
        menu_item_parent: '0',
        object_id: '2431',
        object: 'custom',
        type: 'custom',
        type_label: 'Custom Link',
        title: 'MERN Stack',
        url: '#',
        target: '',
        attr_title: 'mern',
        description: '',
        classes: [''],
        xfn: '',
        meta: {},
        acf: {},
        children: [
          {
            ID: 2432,
            post_author: '1',
            post_date: '2022-06-17 04:38:52',
            post_date_gmt: '2022-06-16 11:42:36',
            post_content:
              'MetaJobs is the best Job Board Theme. Built with node.js, MongoDB, React',
            post_title: 'MetaJobs- Job Board Theme',
            post_excerpt: 'Job Board Theme',
            post_status: 'publish',
            comment_status: 'closed',
            ping_status: 'closed',
            post_password: '',
            post_name: 'metajobs-job-board-theme',
            to_ping: '',
            pinged: '',
            post_modified: '2022-06-17 04:38:52',
            post_modified_gmt: '2022-06-17 04:38:52',
            post_content_filtered: '',
            post_parent: 0,
            guid: 'https://api-blog.jstemplate.net/?p=2432',
            menu_order: 2,
            post_type: 'nav_menu_item',
            post_mime_type: '',
            comment_count: '0',
            filter: 'raw',
            db_id: 2432,
            menu_item_parent: '2431',
            object_id: '2432',
            object: 'custom',
            type: 'custom',
            type_label: 'Custom Link',
            title: 'MetaJobs- Job Board Theme',
            url: '/item/mern-stack-job-board-theme',
            target: '',
            attr_title: 'Job Board Theme',
            description:
              'MetaJobs is the best Job Board Theme. Built with node.js, MongoDB, React',
            classes: [
              'FaShoppingCart',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              '',
              'classNamew-6',
              'h-6',
              'drop-shadow-lg',
              'text-orangeTwo',
              '',
            ],
            xfn: '',
            meta: {},
            acf: {},
          },
          {
            ID: 2433,
            post_author: '1',
            post_date: '2022-06-17 04:38:52',
            post_date_gmt: '2022-06-16 11:42:36',
            post_content:
              'MetaAds is the best Classified Ads Theme. Built with node.js, MongoDB, React',
            post_title: 'MetaAds- Classified Ads Theme',
            post_excerpt: 'Classified Ads Theme',
            post_status: 'publish',
            comment_status: 'closed',
            ping_status: 'closed',
            post_password: '',
            post_name: 'metaads-classified-ads-theme',
            to_ping: '',
            pinged: '',
            post_modified: '2022-06-17 04:38:52',
            post_modified_gmt: '2022-06-17 04:38:52',
            post_content_filtered: '',
            post_parent: 0,
            guid: 'https://api-blog.jstemplate.net/?p=2433',
            menu_order: 3,
            post_type: 'nav_menu_item',
            post_mime_type: '',
            comment_count: '0',
            filter: 'raw',
            db_id: 2433,
            menu_item_parent: '2431',
            object_id: '2433',
            object: 'custom',
            type: 'custom',
            type_label: 'Custom Link',
            title: 'MetaAds- Classified Ads Theme',
            url: '/item/mern-stack-classified-ads-theme',
            target: '',
            attr_title: 'Classified Ads Theme',
            description:
              'MetaAds is the best Classified Ads Theme. Built with node.js, MongoDB, React',
            classes: [''],
            xfn: '',
            meta: {},
            acf: {},
          },
        ],
      },
      {
        ID: 2435,
        post_author: '1',
        post_date: '2022-06-17 04:38:52',
        post_date_gmt: '2022-06-16 11:45:33',
        post_content: '',
        post_title: 'Frontity Theme',
        post_excerpt: 'headless',
        post_status: 'publish',
        comment_status: 'closed',
        ping_status: 'closed',
        post_password: '',
        post_name: 'frontity-theme-2',
        to_ping: '',
        pinged: '',
        post_modified: '2022-06-17 04:38:52',
        post_modified_gmt: '2022-06-17 04:38:52',
        post_content_filtered: '',
        post_parent: 0,
        guid: 'https://api-blog.jstemplate.net/?p=2435',
        menu_order: 4,
        post_type: 'nav_menu_item',
        post_mime_type: '',
        comment_count: '0',
        filter: 'raw',
        db_id: 2435,
        menu_item_parent: '0',
        object_id: '2435',
        object: 'custom',
        type: 'custom',
        type_label: 'Custom Link',
        title: 'Frontity Theme',
        url: '#',
        target: '',
        attr_title: 'headless',
        description: '',
        classes: [''],
        xfn: '',
        meta: {},
        acf: {},
        children: [
          {
            ID: 2436,
            post_author: '1',
            post_date: '2022-06-17 04:38:52',
            post_date_gmt: '2022-06-16 11:45:33',
            post_content:
              'Best Personal Portfolio Theme with WordPress and React',
            post_title: 'Personal Portfolio Theme',
            post_excerpt: '',
            post_status: 'publish',
            comment_status: 'closed',
            ping_status: 'closed',
            post_password: '',
            post_name: 'personal-portfolio-theme',
            to_ping: '',
            pinged: '',
            post_modified: '2022-06-17 04:38:52',
            post_modified_gmt: '2022-06-17 04:38:52',
            post_content_filtered: '',
            post_parent: 0,
            guid: 'https://api-blog.jstemplate.net/?p=2436',
            menu_order: 5,
            post_type: 'nav_menu_item',
            post_mime_type: '',
            comment_count: '0',
            filter: 'raw',
            db_id: 2436,
            menu_item_parent: '2435',
            object_id: '2436',
            object: 'custom',
            type: 'custom',
            type_label: 'Custom Link',
            title: 'Personal Portfolio Theme',
            url: '/item/portfo-frontity-personal-portfolio-theme',
            target: '',
            attr_title: '',
            description:
              'Best Personal Portfolio Theme with WordPress and React',
            classes: [''],
            xfn: '',
            meta: {},
            acf: {},
          },
          {
            ID: 2437,
            post_author: '1',
            post_date: '2022-06-17 04:38:52',
            post_date_gmt: '2022-06-16 11:45:33',
            post_content: 'Headless WordPress theme with Eementor and React',
            post_title: 'Multipurpose Frontity Theme',
            post_excerpt: '',
            post_status: 'publish',
            comment_status: 'closed',
            ping_status: 'closed',
            post_password: '',
            post_name: 'multipurpose-frontity-theme',
            to_ping: '',
            pinged: '',
            post_modified: '2022-06-17 04:38:52',
            post_modified_gmt: '2022-06-17 04:38:52',
            post_content_filtered: '',
            post_parent: 0,
            guid: 'https://api-blog.jstemplate.net/?p=2437',
            menu_order: 6,
            post_type: 'nav_menu_item',
            post_mime_type: '',
            comment_count: '0',
            filter: 'raw',
            db_id: 2437,
            menu_item_parent: '2435',
            object_id: '2437',
            object: 'custom',
            type: 'custom',
            type_label: 'Custom Link',
            title: 'Multipurpose Frontity Theme',
            url: '#',
            target: '',
            attr_title: '',
            description: 'Headless WordPress theme with Eementor and React',
            classes: [''],
            xfn: '',
            meta: {},
            acf: {},
          },
        ],
      },
      {
        ID: 2438,
        post_author: '1',
        post_date: '2022-06-17 04:38:52',
        post_date_gmt: '2022-06-16 11:45:33',
        post_content: '',
        post_title: 'React Template',
        post_excerpt: 'react',
        post_status: 'publish',
        comment_status: 'closed',
        ping_status: 'closed',
        post_password: '',
        post_name: 'react-template',
        to_ping: '',
        pinged: '',
        post_modified: '2022-06-17 04:38:52',
        post_modified_gmt: '2022-06-17 04:38:52',
        post_content_filtered: '',
        post_parent: 0,
        guid: 'https://api-blog.jstemplate.net/?p=2438',
        menu_order: 7,
        post_type: 'nav_menu_item',
        post_mime_type: '',
        comment_count: '0',
        filter: 'raw',
        db_id: 2438,
        menu_item_parent: '0',
        object_id: '2438',
        object: 'custom',
        type: 'custom',
        type_label: 'Custom Link',
        title: 'React Template',
        url: '#',
        target: '',
        attr_title: 'react',
        description: '',
        classes: [''],
        xfn: '',
        meta: {},
        acf: {},
        children: [
          {
            ID: 2441,
            post_author: '1',
            post_date: '2022-06-17 04:38:52',
            post_date_gmt: '2022-06-16 17:19:46',
            post_content:
              'Multipurpose React Template to buid your site quickly',
            post_title: 'Multipurpose React Template',
            post_excerpt: '',
            post_status: 'publish',
            comment_status: 'closed',
            ping_status: 'closed',
            post_password: '',
            post_name: 'multipurpose-react-template',
            to_ping: '',
            pinged: '',
            post_modified: '2022-06-17 04:38:52',
            post_modified_gmt: '2022-06-17 04:38:52',
            post_content_filtered: '',
            post_parent: 0,
            guid: 'https://api-blog.jstemplate.net/?p=2441',
            menu_order: 8,
            post_type: 'nav_menu_item',
            post_mime_type: '',
            comment_count: '0',
            filter: 'raw',
            db_id: 2441,
            menu_item_parent: '2438',
            object_id: '2441',
            object: 'custom',
            type: 'custom',
            type_label: 'Custom Link',
            title: 'Multipurpose React Template',
            url: '#',
            target: '',
            attr_title: '',
            description:
              'Multipurpose React Template to buid your site quickly',
            classes: [''],
            xfn: '',
            meta: {},
            acf: {},
          },
          {
            ID: 2444,
            post_author: '1',
            post_date: '2022-06-17 04:38:52',
            post_date_gmt: '2022-06-16 19:07:16',
            post_content: 'Best React Admin Dashboard Template',
            post_title: 'React Admin Dashboard Template',
            post_excerpt: '',
            post_status: 'publish',
            comment_status: 'closed',
            ping_status: 'closed',
            post_password: '',
            post_name: 'react-admin-dashboard-template',
            to_ping: '',
            pinged: '',
            post_modified: '2022-06-17 04:38:52',
            post_modified_gmt: '2022-06-17 04:38:52',
            post_content_filtered: '',
            post_parent: 0,
            guid: 'https://api-blog.jstemplate.net/?p=2444',
            menu_order: 9,
            post_type: 'nav_menu_item',
            post_mime_type: '',
            comment_count: '0',
            filter: 'raw',
            db_id: 2444,
            menu_item_parent: '2438',
            object_id: '2444',
            object: 'custom',
            type: 'custom',
            type_label: 'Custom Link',
            title: 'React Admin Dashboard Template',
            url: '#',
            target: '',
            attr_title: '',
            description: 'Best React Admin Dashboard Template',
            classes: [''],
            xfn: '',
            meta: {},
            acf: {},
          },
        ],
      },
      {
        ID: 2439,
        post_author: '1',
        post_date: '2022-06-17 04:38:52',
        post_date_gmt: '2022-06-16 11:45:33',
        post_content: '',
        post_title: 'Tailwind CSS',
        post_excerpt: 'figma',
        post_status: 'publish',
        comment_status: 'closed',
        ping_status: 'closed',
        post_password: '',
        post_name: 'tailwind-css',
        to_ping: '',
        pinged: '',
        post_modified: '2022-06-17 04:38:52',
        post_modified_gmt: '2022-06-17 04:38:52',
        post_content_filtered: '',
        post_parent: 0,
        guid: 'https://api-blog.jstemplate.net/?p=2439',
        menu_order: 10,
        post_type: 'nav_menu_item',
        post_mime_type: '',
        comment_count: '0',
        filter: 'raw',
        db_id: 2439,
        menu_item_parent: '0',
        object_id: '2439',
        object: 'custom',
        type: 'custom',
        type_label: 'Custom Link',
        title: 'Tailwind CSS',
        url: '#',
        target: '',
        attr_title: 'figma',
        description: '',
        classes: [''],
        xfn: '',
        meta: {},
        acf: {},
        children: [
          {
            ID: 2442,
            post_author: '1',
            post_date: '2022-06-17 04:38:52',
            post_date_gmt: '2022-06-16 19:02:38',
            post_content:
              'Start coding with our pre-made Tailwind CSS components',
            post_title: 'Free Tailwind CSS UI Components',
            post_excerpt: 'tailwind',
            post_status: 'publish',
            comment_status: 'closed',
            ping_status: 'closed',
            post_password: '',
            post_name: 'tailwind-css-ui-components',
            to_ping: '',
            pinged: '',
            post_modified: '2022-06-17 04:38:52',
            post_modified_gmt: '2022-06-17 04:38:52',
            post_content_filtered: '',
            post_parent: 0,
            guid: 'https://api-blog.jstemplate.net/?p=2442',
            menu_order: 11,
            post_type: 'nav_menu_item',
            post_mime_type: '',
            comment_count: '0',
            filter: 'raw',
            db_id: 2442,
            menu_item_parent: '2439',
            object_id: '2442',
            object: 'custom',
            type: 'custom',
            type_label: 'Custom Link',
            title: 'Free Tailwind CSS UI Components',
            url: 'https://www.tailwindkits.com/components',
            target: '',
            attr_title: 'tailwind',
            description:
              'Start coding with our pre-made Tailwind CSS components',
            classes: [''],
            xfn: '',
            meta: {},
            acf: {},
          },
          {
            ID: 2443,
            post_author: '1',
            post_date: '2022-06-17 04:38:52',
            post_date_gmt: '2022-06-16 19:02:38',
            post_content:
              'Download professional Ready-Made Tailwind CSS Landing Pages',
            post_title: '100+ Tailwind CSS Landing Pages',
            post_excerpt: '',
            post_status: 'publish',
            comment_status: 'closed',
            ping_status: 'closed',
            post_password: '',
            post_name: 'tailwind-css-landing-pages',
            to_ping: '',
            pinged: '',
            post_modified: '2022-06-17 04:38:52',
            post_modified_gmt: '2022-06-17 04:38:52',
            post_content_filtered: '',
            post_parent: 0,
            guid: 'https://api-blog.jstemplate.net/?p=2443',
            menu_order: 12,
            post_type: 'nav_menu_item',
            post_mime_type: '',
            comment_count: '0',
            filter: 'raw',
            db_id: 2443,
            menu_item_parent: '2439',
            object_id: '2443',
            object: 'custom',
            type: 'custom',
            type_label: 'Custom Link',
            title: '100+ Tailwind CSS Landing Pages',
            url: 'https://www.tailwindkits.com/landing-pages',
            target: '',
            attr_title: '',
            description:
              'Download professional Ready-Made Tailwind CSS Landing Pages',
            classes: [''],
            xfn: '',
            meta: {},
            acf: {},
          },
        ],
      },
    ]
    //   filder parent menu items and child menu items
    const categoryMenu = _.filter( data, ( item: any ) => {
      return item.post_type === 'nav_menu_item'
    } ).map( ( item: any ) => {
      return {
        id: item.ID,
        title: item.title,
        menu_order: item.menu_order,
        attr_title: item.attr_title,
        // slice url to get only the slug
        url: item.url,

        children: item.children?.map( ( child: any ) => {
          return {
            id: child.ID,
            title: child.title,
            description: child.post_content,
            url: child.url,
            iconClass: child.classes[0],
          }
        } ),
      }
    } )

    return res.status( 200 ).send( {
      message: 'Successfully fetched menus',
      data: categoryMenu,
    } )
  } catch ( error: any ) {
    return res.status( 500 ).send( { message: error.message } )
  }
}
